CREATE TABLE IF NOT EXISTS assets (
                                      id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                      name VARCHAR(30) NOT NULL UNIQUE
    );


CREATE TABLE IF NOT EXISTS rates (
                                     id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                     value DOUBLE PRECISION NOT NULL,
                                     asset_id INT UNIQUE,
                                     FOREIGN KEY (asset_id) REFERENCES assets(id) ON DELETE CASCADE
    );